ALTER TABLE findings ADD COLUMN IF NOT EXISTS severity TEXT NOT NULL DEFAULT '';
ALTER TABLE findings ADD COLUMN IF NOT EXISTS owasp_category TEXT NOT NULL DEFAULT 'UNCATEGORIZED';
ALTER TABLE findings ADD COLUMN IF NOT EXISTS group_id UUID;
ALTER TABLE findings ADD COLUMN IF NOT EXISTS reproducibility DOUBLE PRECISION NOT NULL DEFAULT 0;
CREATE INDEX IF NOT EXISTS idx_findings_group_id ON findings(group_id);
